import React from 'react';
import { X, Sparkles, ArrowRight } from 'lucide-react';

interface TourModalProps {
  isOpen: boolean;
  onClose: () => void;
  onSelectTab: (tabId: string) => void;
}

const TOUR_STEPS = [
  {
    tabId: 'dashboard',
    title: 'Dashboard & Spatial Simulation',
    desc: 'See the live Bengaluru hub map with 800 grid coordinate nodes and optimal warehouse placement generated by the discrete facility location solver.',
  },
  {
    tabId: 'dashboard',
    title: 'Run Optimization Solver',
    desc: 'Tune warehouse counts (1–10), budgets, and electric vehicle fleet transitions. Watch micro-hubs get selected in real time.',
  },
  {
    tabId: 'scenarios',
    title: 'Scenario Stress Testing',
    desc: 'Test High Demand surges (+40%), Monsoon Weather disruptions, and Outer Ring Road peak traffic with instant SLA comparisons.',
  },
  {
    tabId: 'analytics',
    title: 'Analytics & ESG Benchmarks',
    desc: 'Explore quick-commerce SLA fulfillment, EV petrol cost savings vs charging, and CO₂ emission reductions across Bengaluru corridors.',
  },
  {
    tabId: 'data',
    title: 'BBMP Demand Grid & Localities',
    desc: 'Inspect the 800 discrete BBMP ward points, localized price benchmarks, and demand density matrices loaded from the dataset.',
  },
];

export const TourModal: React.FC<TourModalProps> = ({ isOpen, onClose, onSelectTab }) => {
  if (!isOpen) return null;

  return (
    <div className="modal-overlay" onClick={onClose}>
      <div className="tour-modal" onClick={(e) => e.stopPropagation()}>
        <button className="modal-close" onClick={onClose}>
          <X size={18} />
        </button>

        <div style={{ display: 'flex', alignItems: 'center', gap: '.75rem', marginBottom: '1.25rem' }}>
          <div
            style={{
              width: '40px',
              height: '40px',
              borderRadius: '12px',
              background: '#FFF8EE',
              border: '1px solid #E9CDB0',
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'center',
              color: '#9E471A',
            }}
          >
            <Sparkles size={18} />
          </div>
          <div>
            <div style={{ fontFamily: "'Cormorant Garamond', serif", fontSize: '1.3rem', fontWeight: 700, color: '#261B14' }}>
              Interactive Demo Tour
            </div>
            <div style={{ fontSize: '.7rem', color: '#7A7168' }}>
              Explore every feature of Namma Warehouse
            </div>
          </div>
        </div>

        <div style={{ marginTop: '1rem', marginBottom: '1.25rem' }}>
          {TOUR_STEPS.map((s, i) => (
            <div
              key={i}
              className="tour-step"
              onClick={() => {
                onSelectTab(s.tabId);
                onClose();
              }}
            >
              <div className="tour-step-num">{i + 1}</div>
              <div>
                <div className="tour-step-title">{s.title}</div>
                <div className="tour-step-desc">{s.desc}</div>
              </div>
            </div>
          ))}
        </div>

        <button
          className="btn-submit"
          style={{ width: '100%', justifyContent: 'center' }}
          onClick={() => {
            onSelectTab('dashboard');
            onClose();
          }}
        >
          Start Exploring
          <ArrowRight size={14} />
        </button>
      </div>
    </div>
  );
};
